Traceback (most recent call last):
  File "/home/sano_anju/errlocator/sample/FileNotFoundError/f01.py", line 3, in <module>
    with open(filename, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'