Traceback (most recent call last):
  File "/home/sano_anju/errlocator/sample/AssertionError/as01.py", line 3, in <module>
    assert number2 != 0, "Invalid Operation"
           ^^^^^^^^^^^^
AssertionError: Invalid Operation