Traceback (most recent call last):
  File "/home/sano_anju/01/sample/ValueError/v03.py", line 5, in <module>
    math.log(num)
ValueError: math domain error